version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  frontend:
    docker:
      - image: circleci/node:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          command: | 
            cd frontend
            npm i
            npm run test
workflows:
  node-tests:
    jobs:
      - frontend
